questions = [
    (1, "Office Management Software", "Does the applicant have experience with office management software (e.g., Microsoft Office Suite, Google Workspace)?", 6),
    (2, "Filing Systems", "Is there evidence of skills in managing electronic and physical filing systems?", 5),
    (3, "Scheduling and Calendar Management", "Can the applicant handle scheduling and calendar management efficiently?", 5),
    (4, "Communication Tools", "Has the applicant demonstrated proficiency in communication tools and technologies (e.g., Slack, Zoom)?", 5),
    (5, "Advanced Skills", "Are there advanced skills noted that are relevant to administrative work, such as budgeting software or CRM systems?", 4),
    (6, "Years of Experience", "Has the applicant worked in administrative roles? How long has the applicant worked in administrative roles?", 6),
    (7, "Progressive Responsibility", "Does the applicant's work history show progressive responsibility in administrative tasks?", 5),
    (8, "Process Improvements", "Are there specific examples of projects where the applicant improved office processes or efficiency?", 5),
    (9, "Cross-Departmental Coordination", "Has the applicant managed or coordinated cross-departmental administrative efforts?", 5),
    (10, "Confidential Information", "Is there experience in handling confidential or sensitive information?", 4),
    (11, "Professional Expertise", "Does the professional summary clearly articulate the applicant's expertise in administrative functions?", 4),
    (12, "Quantifiable Impacts", "Are there quantifiable impacts mentioned in the CV that demonstrate improvements in office operations or efficiency?", 5),
    (13, "Approach to Challenges", "Does the applicant describe their approach to administrative challenges? How?", 4),
    (14, "Leadership and Initiative", "Is there evidence of leadership or initiative in taking on administrative projects?", 4),
    (15, "Proactive Approach", "Does the CV reflect a proactive approach to optimizing administrative processes?", 3),
    (16, "Formal Education", "Does the applicant have formal education in business administration or a related field?", 4),
    (17, "Continuing Education", "Has the applicant participated in any continuing education courses relevant to administration (e.g., project management, office technology)?", 3),
    (18, "Certifications", "Are there certifications that support administrative skills (e.g., Certified Administrative Professional)?", 4),
    (19, "Educational Background", "Does the applicant’s educational background support their proficiency in administrative tasks?", 2),
    (20, "Academic Projects", "Are there academic projects or roles that demonstrate organizational skills?", 2),
    (21, "Organizational Skills", "Does the CV highlight organizational skills that are essential for administrative roles?", 3),
    (22, "Interpersonal Communication", "Is there evidence of strong interpersonal communication skills?", 3),
    (23, "Multitasking and Prioritization", "Does the applicant handle multitasking and prioritization, as described in the CV?", 3),
    (24, "Working Under Pressure", "Are there examples of the applicant working effectively under pressure?", 3),
    (25, "Cultural Alignment", "Does the CV reflect alignment with the company's core values and culture, particularly in terms of teamwork and support?", 3)
]