questions = [
    (1, "Creative Skills", "Does the applicant list specific creative skills mentioned in the job description, such as graphic design, video editing, or creative writing?", 6),
    (2, "Projects and Tasks", "Are there examples of projects or tasks in the CV where these creative skills were applied?", 5),
    (3, "Skill Proficiency", "Are the mentioned creative skills advanced? Are there any portfolios, exhibitions, or published works that demonstrate proficiency?", 5),
    (4, "Preferred Tools", "Does the CV mention familiarity with industry-standard creative tools and technologies (e.g., Adobe Creative Suite, Final Cut Pro)?", 5),
    (5, "Additional Skills", "Are there any additional creative skills listed that could be beneficial for the role but are not explicitly mentioned in the job description?", 4),
    (6, "Years of Experience", "How many years of relevant creative industry experience does the applicant have compared to what is required? Is there a significant difference?", 6),
    (7, "Project Relevance", "Can the projects listed in the work experience be directly linked to the creative tasks outlined in the job description?", 6),
    (8, "Role Demonstrations", "Are there descriptions of past roles or projects that demonstrate the applicant's ability to fulfill the role’s creative expectations?", 5),
    (9, "Progression and Contributions", "Does the applicant show progression or significant contributions in their creative field that align with the level of this position?", 5),
    (10, "Industry Experience", "Is there evidence of experience in the specific creative industry or domain of the new role?", 4),
    (11, "Professional Expertise", "Does the professional summary clearly articulate the applicant’s creative expertise in areas crucial for the job?", 4),
    (12, "Quantifiable Impacts", "Are there quantifiable impacts mentioned in the CV that align with the creative responsibilities of the new role (e.g., campaigns led, viewership increases)?", 5),
    (13, "High-Priority Tasks", "Do the projects listed demonstrate the applicant's capability to handle the high-priority creative tasks of the new role?", 4),
    (14, "Leadership and Innovations", "Is there evidence of leadership in creative projects or innovations that brought significant changes or enhancements to previous employers?", 4),
    (15, "Company Contributions", "Does the CV reflect a clear understanding of the company’s goals and how the applicant can contribute creatively to them?", 3),
    (16, "Educational Degrees", "Does the applicant have the degree(s) required or preferred for the position in a relevant creative field?", 3),
    (17, "Field of Study", "Is the field of study relevant to the technical and theoretical knowledge needed for creative positions?", 3),
    (18, "Continuous Learning", "Has the applicant engaged in any continuous learning or advanced education that enhances their suitability for the creative role?", 3),
    (19, "Technical Expertise", "Does the applicant’s educational background support their expertise in required creative technical areas?", 3),
    (20, "Academic Achievements", "Are there any academic achievements or projects that demonstrate the applicant’s commitment to learning and growth in the creative field?", 3),
    (21, "Soft Skills", "Does the CV reflect key soft skills required for the position such as creativity, collaboration, and innovation?", 3),
    (22, "Collaboration", "Are there mentions of teamwork or projects that required cross-functional collaboration within creative contexts?", 3),
    (23, "Teamwork Approach", "Does the applicant describe their approach to creative challenges or teamwork? Does this align with the company’s values?", 3),
    (24, "Cultural Alignment", "Are there any volunteer activities, memberships, or interests listed that resonate with the company's culture or values in a creative industry?", 3),
    (25, "Motivation and Passion", "Does the applicant express their motivation and passion for the creative field, and does it align with the company's mission and vision?", 3)
]