questions = [
    (1, "Customer Service Skills", "Does the applicant list specific customer service skills mentioned in the job description? (e.g., CRM software proficiency, communication skills)", 6),
    (2, "Projects and Tasks", "Are there examples of projects or tasks in the CV where these customer service skills were applied?", 5),
    (3, "Skill Proficiency", "How advanced are the mentioned customer service skills? Are there any certifications or training programs completed that demonstrate proficiency?", 5),
    (4, "Customer Service Tools", "Does the CV mention experience with any customer service tools or technologies preferred by the employer? (e.g., Zendesk, Salesforce)", 5),
    (5, "Additional Skills", "Are there any additional skills listed that could be beneficial for the role but are not explicitly mentioned in the job description? (e.g., multilingual capabilities)", 4),
    (6, "Years of Experience", "How many years of customer service experience does the applicant have compared to what is required?", 6),
    (7, "Project Relevance", "Can the projects listed in the work experience be directly linked to the customer service tasks outlined in the job description?", 5),
    (8, "Role Demonstrations", "Are there descriptions of past customer service roles or projects that demonstrate the applicant's ability to fulfill the role’s expectations?", 5),
    (9, "Progression and Contributions", "Does the applicant show progression or significant contributions in their customer service career that align with the level of this position?", 5),
    (10, "Customer Interactions", "Is there evidence of experience in handling the specific types of customer interactions or challenges mentioned in the job description? (e.g., high volume calls, complaint resolution)", 4),
    (11, "Professional Philosophy", "Does the professional summary clearly articulate the applicant’s customer service philosophy and approach?", 5),
    (12, "Quantifiable Impacts", "Are there quantifiable impacts mentioned in the CV that align with the responsibilities of the new role? (e.g., improved customer satisfaction ratings, reduced response times)", 5),
    (13, "High-Priority Tasks", "How do the projects listed demonstrate the applicant's capability to handle high-priority customer service tasks of the new role?", 4),
    (14, "Leadership and Initiatives", "Is there evidence of leadership in customer service projects or initiatives that brought significant improvements to previous employers?", 3),
    (15, "Company Contributions", "Does the CV reflect a clear understanding of the company’s customer service goals and how the applicant can contribute to them?", 3),
    (16, "Formal Education", "Does the applicant have any formal education or training relevant to customer service? (e.g., degrees in communication, hospitality, or relevant certifications)", 4),
    (17, "Field of Study", "Is the field of study relevant to the interpersonal and communication skills needed for the position?", 3),
    (18, "Continuous Learning", "Has the applicant engaged in any continuous learning or training that enhances their suitability for customer service roles?", 3),
    (19, "Educational Background", "How does the applicant’s educational background support their expertise in customer service?", 3),
    (20, "Academic Achievements", "Are there any academic achievements or projects that demonstrate the applicant’s commitment to learning and growth in customer service?", 2),
    (21, "Soft Skills", "Does the CV reflect key soft skills required for the position such as empathy, patience, and active listening?", 4),
    (22, "Collaboration", "Are there mentions of teamwork or projects that required cross-functional collaboration within a customer service setting?", 3),
    (23, "Customer Service Approach", "How does the applicant describe their approach to customer service challenges or teamwork? Does this align with the company’s values?", 3),
    (24, "Cultural Alignment", "Are there any volunteer activities, memberships, or interests listed that resonate with the company's customer service culture or values?", 3),
    (25, "Motivation and Passion", "How does the applicant express their motivation and passion for customer service, and does it align with the company's mission and vision?", 2)
]