questions = [
    (1, "Pedagogical Skills", "Does the CV list pedagogical skills and knowledge specific to the subject area they will be teaching?", 6),
    (2, "Teaching Strategies", "Are there proven methodologies or teaching strategies mentioned that align with modern educational practices?", 6),
    (3, "Educational Technology", "How proficient is the applicant with educational technology and digital tools for classroom management and online teaching?", 5),
    (4, "Certifications", "Does the applicant possess necessary certifications such as teaching credentials or specialized training relevant to the role?", 5),
    (5, "Additional Skills", "Are additional skills like curriculum development or educational research mentioned?", 3),
    (6, "Years of Experience", "How many years of teaching or training experience does the applicant have in relevant educational settings?", 6),
    (7, "Learning Environments", "Can the applicant demonstrate experience with diverse learning environments and student populations?", 5),
    (8, "Program Initiatives", "Are there examples of specific educational programs or initiatives that the applicant successfully implemented or contributed to?", 5),
    (9, "Leadership Roles", "Does the applicant have experience in educational leadership roles, such as department head or curriculum coordinator?", 5),
    (10, "Professional Development", "Is there evidence of ongoing professional development in the field of education?", 4),
    (11, "Teaching Philosophy", "Does the professional summary articulate a clear teaching philosophy or educational vision?", 5),
    (12, "Quantifiable Achievements", "Are there quantifiable achievements mentioned, such as improvements in student performance or program accreditation results?", 5),
    (13, "Student Engagement", "How does the applicant describe their impact on student engagement and learning outcomes?", 4),
    (14, "Educational Goals", "Is there evidence of contributing to broader educational goals, such as inclusivity or technology integration?", 3),
    (15, "Learning Environment", "Does the CV demonstrate a commitment to fostering a positive and collaborative learning environment?", 3),
    (16, "Education Degrees", "Does the applicant have a degree in education or a closely related field?", 4),
    (17, "Advanced Degrees", "Are advanced degrees or specialized educational qualifications present that enhance their teaching capability?", 4),
    (18, "Educational Workshops", "Has the applicant participated in recent educational workshops or certifications that are relevant to their teaching discipline?", 3),
    (19, "Educational Background", "Does the educational background support areas of expertise claimed in their professional roles?", 2),
    (20, "Academic Achievements", "Are there academic achievements or recognitions that highlight the applicant’s commitment to their educational career?", 2),
    (21, "Soft Skills", "Does the CV reflect essential soft skills for education roles such as communication, empathy, and patience?", 4),
    (22, "Teamwork and Collaboration", "Are there examples of teamwork or collaboration with other educators and administrative staff?", 3),
    (23, "Classroom Management", "How does the applicant describe their approach to classroom management and student interaction?", 3),
    (24, "Extracurricular Activities", "Does the applicant mention involvement in extracurricular activities or school committees?", 3),
    (25, "Institutional Alignment", "How well does the applicant’s values and teaching style align with the educational institution’s culture and philosophy?", 2)
]