questions = [
    (1, "Strategic Planning", "Does the applicant possess advanced skills in strategic planning and execution as outlined in the job description?", 7),
    (2, "Financial Management", "Are there demonstrated skills in financial management or budgeting relevant to the executive role?", 5),
    (3, "Technological Proficiency", "Does the CV highlight proficiency in technologies or systems crucial for high-level management?", 4),
    (4, "Crisis Management", "Are crisis management and decision-making skills evident from the CV?", 5),
    (5, "Regulatory Expertise", "Does the applicant have expertise in industry-specific regulations or compliance issues?", 4),
    (6, "Years of Experience", "How many years of executive-level experience does the applicant have?", 6),
    (7, "Team Leadership", "Does the applicant have experience in leading large teams or managing significant company divisions or projects?", 6),
    (8, "Strategic Initiatives", "Are there examples of successful strategic initiatives or projects led by the applicant?", 5),
    (9, "Company Growth", "Has the applicant demonstrated experience in fostering company growth or turnaround?", 4),
    (10, "Global Experience", "Is there international or global experience relevant to a multinational company's needs?", 4),
    (11, "Professional Summary", "Does the professional summary articulate the applicant's experience in leading and transforming organizations?", 5),
    (12, "Measurable Impacts", "Are there measurable impacts listed that relate directly to improved company performance or profitability?", 4),
    (13, "Innovation and Change", "Does the applicant demonstrate an ability to innovate and drive change within an organization?", 4),
    (14, "Long-Term Planning", "Is there evidence of sustainable long-term planning and execution in their previous roles?", 4),
    (15, "Leadership Philosophy", "How effectively does the CV communicate the applicant's leadership philosophy and its alignment with the company’s goals?", 3),
    (16, "Advanced Degrees", "Does the applicant hold an advanced degree (MBA, PhD) relevant to their executive role?", 5),
    (17, "Professional Education", "Is there evidence of continuous professional education or leadership training?", 3),
    (18, "Field of Study", "How relevant is the applicant’s field of study to the current executive role they are applying for?", 3),
    (19, "Academic Achievements", "Are there notable academic achievements that set the applicant apart as a leader in their field?", 2),
    (20, "Executive Workshops", "Has the applicant participated in executive workshops or think tanks that align with the role's demands?", 2),
    (21, "Communication Skills", "Does the CV reflect exceptional communication and interpersonal skills required for high-level negotiations and partnerships?", 4),
    (22, "Team Leadership", "Are there examples of the applicant effectively leading diverse or cross-functional teams?", 3),
    (23, "Resilience and Adaptability", "How does the applicant demonstrate resilience and adaptability in complex situations?", 3),
    (24, "Corporate Culture", "Are there indications of the applicant's commitment to fostering a positive corporate culture and ethical leadership?", 3),
    (25, "Mission Alignment", "Does the applicant show a strong alignment with the company’s mission and values, possibly through philanthropy or corporate social responsibility initiatives?", 2)
]