questions = [
    (1, "Technical Skills", "Does the applicant possess the technical skills required for operations management (e.g., ERP systems, inventory management software)?", 6),
    (2, "Process Optimization", "Has the applicant demonstrated proficiency in process optimization tools and methodologies (e.g., Lean, Six Sigma)?", 6),
    (3, "Projects and Tasks", "Are there examples of projects where these operational skills were effectively applied?", 4),
    (4, "Certifications", "Does the CV list certifications that are relevant to operational excellence?", 5),
    (5, "Additional Skills", "Are there any additional skills listed that could uniquely benefit the operational role (e.g., project management, crisis management)?", 4),
    (6, "Years of Experience", "How many years of relevant operational experience does the applicant have, and how does this compare to what is required? Is there a significant difference?", 6),
    (7, "Project Relevance", "Can the projects listed in the work experience be directly linked to core operational tasks such as supply chain management, logistics, or production oversight?", 5),
    (8, "Role Demonstrations", "Are there descriptions of roles where the applicant improved operational efficiencies or reduced costs?", 5),
    (9, "Progression in Roles", "Does the applicant show progression in operational roles that align with the seniority of this position?", 5),
    (10, "Team and Department Management", "Is there evidence of the applicant having managed teams or departments within an operational context?", 4),
    (11, "Professional Expertise", "Does the professional summary clearly articulate expertise in operational management?", 4),
    (12, "Quantifiable Impacts", "Are there quantifiable impacts mentioned in the CV that align with the responsibilities of an operational role (e.g., percentage reduction in downtime, improvement in output)?", 5),
    (13, "High-Priority Tasks", "Do the projects listed demonstrate the applicant's capability to handle high-priority operational tasks? How?", 4),
    (14, "Leadership and Initiatives", "Is there evidence of leadership in projects or initiatives that brought significant operational improvements?", 4),
    (15, "Company Contributions", "Does the CV reflect a clear understanding of the company’s operational goals and how the applicant can contribute to them?", 3),
    (16, "Educational Degrees", "Does the applicant have the degree(s) required or preferred for the position, specifically in fields related to operations management, business administration, or engineering?", 4),
    (17, "Field of Study", "Is the field of study relevant to the operational knowledge needed for the position?", 3),
    (18, "Continuous Learning", "Has the applicant engaged in any continuous learning or advanced education that enhances their operational management skills?", 3),
    (19, "Educational Background", "Does the applicant’s educational background support their expertise in critical operational areas?", 3),
    (20, "Academic Projects", "Are there any academic projects or achievements that showcase the applicant’s ability and dedication to operations management?", 2),
    (21, "Soft Skills", "Does the CV reflect key soft skills required for the position, such as decision-making under pressure and adaptability?", 3),
    (22, "Collaboration", "Are there mentions of teamwork or projects that required cross-functional collaboration within an operational setting?", 3),
    (23, "Problem-Solving Approach", "Does the applicant describe their approach to problem-solving and crisis management in an operational context? How?", 3),
    (24, "Cultural Alignment", "Are there any volunteer activities, memberships, or interests listed that resonate with the company's culture or emphasize a commitment to industry standards and practices?", 3),
    (25, "Motivation and Passion", "How does the applicant express their motivation and passion for operational excellence, and does it align with the company's mission and vision?", 3)
]