questions = [
    (1, "Professional Licenses and Certifications", "Does the applicant list specific professional licenses or certifications required for the role?", 6),
    (2, "Projects and Tasks", "Are there examples of projects or tasks in the CV where advanced professional skills were applied?", 5),
    (3, "Skill Proficiency", "Is the applicant proficient with specialized tools or software used in the profession?", 4),
    (4, "Continuous Improvement", "Does the CV demonstrate a continuous improvement of professional skills through training or additional courses?", 5),
    (5, "Interdisciplinary Skills", "Are there any interdisciplinary skills listed that could enhance the applicant's effectiveness in this role?", 5),
    (6, "Years of Experience", "How many years of relevant professional experience does the applicant have compared to what is required? Is there a significant difference?", 6),
    (7, "Progressive Responsibility", "Does the applicant's previous job roles demonstrate an escalation of responsibilities and complexities appropriate for this role?", 6),
    (8, "Role Demonstrations", "Are there descriptions of past roles or projects that clearly align with the specialized tasks of this position?", 5),
    (9, "Team and Project Management", "Has the applicant managed teams or projects that are comparable in size and scope to what the new role entails?", 4),
    (10, "Professional Impact", "Is there evidence of the applicant having a significant impact in their previous professional roles?", 4),
    (11, "Professional Expertise", "Does the professional summary effectively highlight the applicant’s expertise in critical areas of the profession?", 5),
    (12, "Quantifiable Achievements", "Are there quantifiable achievements mentioned in the CV that align with high standards of professional practice?", 5),
    (13, "Contributions to Advancements", "Does the applicant demonstrate their contribution to advancements in their field through research, publications, or presentations? How?", 4),
    (14, "Leadership and Recognition", "Is there evidence of leadership or recognition by professional bodies or in professional communities?", 3),
    (15, "Professional Recognitions", "Does the applicant showcase any patents, awards, or other recognitions that are relevant and prestigious in the profession?", 3),
    (16, "Educational Degrees", "Does the applicant possess the required academic degrees from accredited institutions for the position?", 4),
    (17, "Field of Study", "Is the field of study highly relevant to the technical and theoretical demands of the position?", 4),
    (18, "Continuing Education", "Has the applicant participated in postgraduate education or specialized training that is directly applicable to the role?", 3),
    (19, "Academic Honors", "Are there academic honors or distinctions that underscore the applicant’s commitment and excellence in their field?", 2),
    (20, "Lifelong Learning", "Does the applicant engage in lifelong learning initiatives, such as attending conferences or continued education courses?", 2),
    (21, "Soft Skills", "Does the CV reflect key soft skills like ethical judgment, professional integrity, and dependability?", 4),
    (22, "Communication and Collaboration", "Are there examples of effective communication and collaboration within professional settings?", 3),
    (23, "Ethical Challenges", "Does the applicant describe their approach to ethical challenges or professional dilemmas? How?", 3),
    (24, "Professional Memberships", "Are there mentions of professional memberships, volunteer activities, or contributions to professional communities?", 3),
    (25, "Professional Philosophy", "Does the applicant’s stated professional philosophy align with the company’s mission and ethical standards?", 2)
]