questions = [
    (1, "Technical Skills", "Does the applicant have expertise in specific technical skills crucial for R&D such as statistical analysis, experimental design, or computer simulation?", 6),
    (2, "Innovative Examples", "Are there examples of innovative use or development of new technologies or methodologies in the applicant's CV?", 5),
    (3, "Tool Proficiency", "How proficient is the applicant in using advanced R&D tools and software that are essential in the field?", 5),
    (4, "Interdisciplinary Skills", "Does the CV demonstrate a command of interdisciplinary skills beneficial to R&D projects?", 5),
    (5, "Additional Skills", "Are there any additional skills listed that enhance the applicant's capability to contribute to cutting-edge research?", 4),
    (6, "Years of Experience", "How many years of relevant R&D experience does the applicant have, and how does it compare to what is required for the position?", 6),
    (7, "Project Relevance", "Can the projects listed in the work experience be directly linked to major R&D tasks such as product development, clinical trials, or scientific research?", 5),
    (8, "Innovative Roles", "Are there descriptions of past roles or projects that demonstrate the applicant's ability to innovate and push boundaries in their field?", 5),
    (9, "Progression in Roles", "Does the applicant show a history of increasing responsibility in R&D roles that align with the level of this position?", 5),
    (10, "Contributions to Research", "Is there evidence of the applicant’s contribution to patents, publications, or presentations at major conferences?", 4),
    (11, "Professional Summary", "Does the professional summary clearly articulate the applicant’s expertise and unique contributions to R&D?", 5),
    (12, "Quantifiable Impacts", "Are there quantifiable impacts mentioned in the CV that demonstrate significant advancements or breakthroughs in their field?", 5),
    (13, "Leadership in R&D", "How do the projects listed demonstrate the applicant's capability to lead R&D efforts and manage complex research agendas?", 5),
    (14, "Awards and Recognitions", "Is there evidence of the applicant receiving grants, awards, or other recognitions for their R&D work?", 3),
    (15, "Global Trends", "Does the CV reflect an understanding of global trends in R&D that aligns with the company’s strategic goals?", 2),
    (16, "Relevant Degrees", "Does the applicant possess the necessary academic degrees for the position, preferably in a relevant scientific or engineering field?", 4),
    (17, "Field of Study", "Is the field of study particularly relevant to the specialized knowledge needed for advanced R&D work?", 3),
    (18, "Advanced Education", "Has the applicant pursued further education or training that is directly applicable to R&D such as advanced degrees or specialized certifications?", 3),
    (19, "Educational Background", "How does the applicant’s educational background support their expertise in highly technical or specialized areas of R&D?", 3),
    (20, "Academic Projects", "Are there any academic projects or thesis work that directly contribute to their proficiency in R&D?", 2),
    (21, "Problem-Solving Skills", "How does the CV illustrate the applicant's problem-solving skills in complex and uncertain R&D environments?", 3),
    (22, "Teamwork and Collaboration", "Are there examples of teamwork or interdisciplinary collaboration critical for success in R&D projects?", 3),
    (23, "Creative Thinking", "Does the applicant demonstrate a capacity for creative thinking and innovation as described in their approach to past challenges?", 3),
    (24, "Leadership Examples", "Are there any mentions of leadership in collaborative projects or mentorship of junior researchers?", 3),
    (25, "Ethical Practices", "How does the applicant express their commitment to ethical research practices and continuous learning within the R&D community?", 3)
]