questions = [
    (1, "Marketing and Sales Skills", "Does the CV list specific marketing or sales skills mentioned in the job description such as digital marketing, SEO/SEM, or strategic sales techniques?", 5),
    (2, "Campaigns and Strategies", "Are there examples of successful marketing campaigns or sales strategies executed by the applicant?", 6),
    (3, "Tool Proficiency", "Does the applicant demonstrate proficiency in marketing tools and platforms like Google Analytics, CRM software, or sales automation tools?", 5),
    (4, "Content Creation", "Does the CV mention experience with content creation, social media management, or other relevant marketing activities?", 4),
    (5, "Additional Skills", "Are there any additional skills listed that could be uniquely beneficial for the role, such as multilingual capabilities or advanced data analysis skills?", 5),
    (6, "Years of Experience", "How many years of direct sales or marketing experience does the applicant have?", 5),
    (7, "Project Relevance", "Can the projects listed in the work experience be directly linked to generating revenue or building brand awareness?", 6),
    (8, "Sales Targets", "Does the CV show a history of meeting or exceeding sales targets or achieving high ROI on marketing campaigns?", 5),
    (9, "Progression in Roles", "Is there a clear progression in sales or marketing roles, indicating increased responsibility and skill?", 5),
    (10, "Industry Experience", "Does the applicant have experience in the specific industry of the job (e.g., tech, retail, healthcare)?", 4),
    (11, "Professional Summary", "Does the professional summary effectively highlight the applicant’s key strengths in sales/marketing achievements?", 4),
    (12, "Quantifiable Impacts", "Are there quantifiable impacts mentioned, such as percentage growth in sales or increased market share?", 5),
    (13, "Strategic Alignment", "How do the described projects align with the strategic goals of the prospective company?", 4),
    (14, "Leadership Experience", "Is there evidence of leadership in driving sales teams or marketing projects?", 4),
    (15, "Competitive Landscape", "Does the CV articulate a clear understanding of the competitive landscape and how to effectively position the company?", 3),
    (16, "Relevant Degrees", "Does the applicant have a degree in a relevant field such as Business, Marketing, Communications, or similar?", 3),
    (17, "Specialized Training", "Has the applicant participated in specialized training or certification courses in sales or marketing?", 3),
    (18, "Educational Background", "How relevant is the applicant's educational background to the current marketing or sales methodologies?", 3),
    (19, "Academic Projects", "Are there any academic projects or coursework that demonstrate the applicant's passion and skill in sales or marketing?", 3),
    (20, "Professional Development", "Is there evidence of continuous professional development in the field of sales or marketing?", 3),
    (21, "Soft Skills", "Does the CV reflect key soft skills such as persuasive communication, teamwork, and resilience?", 3),
    (22, "Negotiation Skills", "Are there examples of successful negotiation or conflict resolution in a sales or marketing context?", 3),
    (23, "Client Relationships", "How does the applicant describe their approach to maintaining client relationships or managing teams?", 3),
    (24, "Professional Memberships", "Are there any volunteer activities or memberships in professional organizations that highlight a commitment to the sales/marketing community?", 3),
    (25, "Mission Alignment", "Does the applicant express a clear motivation and alignment with the company’s mission, especially in relation to customer satisfaction and market expansion?", 3)
]