questions = [
    (1, "Non-Profit Skills", "Does the CV list specific skills relevant to non-profit roles such as grant writing, fundraising, and advocacy?", 6),
    (2, "Project Examples", "Are there examples of projects in the CV where these non-profit specific skills were successfully applied?", 6),
    (3, "Skill Proficiency", "How advanced are the mentioned skills related to non-profit management and service delivery?", 4),
    (4, "Tool Proficiency", "Does the applicant have skills in using tools and technologies that are important for non-profit operations (e.g., donor databases, social media for advocacy)?", 5),
    (5, "Additional Skills", "Are there any additional skills listed that could uniquely benefit a non-profit role, such as multilingual capabilities or digital marketing?", 4),
    (6, "Years of Experience", "How many years of relevant experience in non-profit or social service sectors does the applicant have?", 5),
    (7, "Project Relevance", "Can the projects listed in the work experience be directly linked to key tasks in non-profit roles (e.g., community outreach, program development)?", 6),
    (8, "Resource Mobilization", "Are there descriptions of past roles where the applicant has demonstrated ability to mobilize resources and manage community projects?", 5),
    (9, "Progression in Roles", "Does the applicant show progression in non-profit roles or significant contributions to their organizations?", 5),
    (10, "Advocacy Involvement", "Is there evidence of direct involvement in advocacy or community engagement initiatives?", 4),
    (11, "Professional Summary", "Does the professional summary articulate the applicant’s commitment to social change or community impact?", 5),
    (12, "Quantifiable Impacts", "Are there quantifiable impacts mentioned in the CV that align with the goals of non-profit organizations (e.g., funds raised, awareness campaigns led)?", 5),
    (13, "Initiative Management", "How do the projects listed demonstrate the applicant's capability to manage and lead initiatives that align with the non-profit's mission?", 5),
    (14, "Leadership Examples", "Is there evidence of leadership in projects or initiatives that brought significant social changes?", 3),
    (15, "Sector Challenges", "Does the CV reflect a clear understanding of the sector’s challenges and how the applicant can address them?", 2),
    (16, "Relevant Degrees", "Does the applicant have a degree in a field relevant to social services or non-profit management (e.g., Social Work, Public Administration)?", 4),
    (17, "Field of Study", "Is the field of study directly applicable to managing non-profit programs or services?", 3),
    (18, "Continuous Learning", "Has the applicant engaged in any continuous learning or training specific to non-profit sectors, such as workshops in community leadership or fundraising certifications?", 4),
    (19, "Educational Background", "How does the applicant’s educational background support their understanding of non-profit challenges?", 2),
    (20, "Academic Projects", "Are there any academic projects or papers focused on social issues, policy, or community development?", 2),
    (21, "Soft Skills", "Does the CV reflect key soft skills required for non-profit positions such as empathy, communication, and collaboration?", 3),
    (22, "Teamwork and Collaboration", "Are there mentions of teamwork or roles that required building partnerships with other organizations or community groups?", 3),
    (23, "Problem-Solving Approach", "How does the applicant describe their approach to solving community or organizational challenges?", 3),
    (24, "Volunteer Activities", "Are there any volunteer activities, board memberships, or roles in community organizations that highlight a commitment to social values?", 3),
    (25, "Mission Alignment", "How does the applicant express their motivation for working in the non-profit sector and how does it align with the organization's mission and values?", 3)
]