questions = [
    (1, "Technical Skills", "Does the applicant list specific technical skills mentioned in the job description (e.g., programming languages, software tools, technologies)?", 6),
    (2, "Projects and Tasks", "Are there examples of projects or tasks in the CV where these skills were applied?", 5),
    (3, "Skill Proficiency", "How advanced are the mentioned skills? Are there any certifications, courses, or projects that demonstrate proficiency?", 5),
    (4, "Preferred Tools", "Does the CV mention any of the preferred technical tools or technologies?", 5),
    (5, "Additional Skills", "Are there any additional skills listed that could be beneficial for the role but are not explicitly mentioned in the job description?", 4),
    (6, "Years of Experience", "How many years of relevant professional experience does the applicant have compared to what is required? Is there a significant difference?", 6),
    (7, "Project Relevance", "Can the projects listed in the work experience be directly linked to the tasks outlined in the job description?", 6),
    (8, "Role Demonstrations", "Are there descriptions of past roles or projects that demonstrate the applicant's ability to fulfill the role’s expectations?", 5),
    (9, "Progression and Contributions", "Does the applicant show progression or significant contributions in their field that align with the level of this position?", 4),
    (10, "Industry Experience", "Is there evidence of experience in the specific industry or domain of the new role?", 4),
    (11, "Professional Expertise", "Does the professional summary clearly articulate the applicant’s expertise in areas crucial for the job?", 5),
    (12, "Quantifiable Impacts", "Are there quantifiable impacts mentioned in the CV that align with the responsibilities of the new role?", 5),
    (13, "High-Priority Tasks", "Do the projects listed demonstrate the applicant's capability to handle the high-priority tasks of the new role?", 5),
    (14, "Leadership and Innovations", "Is there evidence of leadership in projects or innovations that brought significant changes or enhancements to previous employers?", 3),
    (15, "Company Contributions", "Does the CV reflect a clear understanding of the company’s goals and how the applicant can contribute to them?", 2),
    (16, "Educational Degrees", "Does the applicant have the degree(s) required or preferred for the position?", 4),
    (17, "Field of Study", "Is the field of study relevant to the technical and theoretical knowledge needed for the position?", 4),
    (18, "Continuous Learning", "Has the applicant engaged in any continuous learning or advanced education that enhances their suitability for the role?", 3),
    (19, "Technical Expertise", "Does the applicant’s educational background support their expertise in required technical areas?", 2),
    (20, "Academic Achievements", "Are there any academic achievements or projects that demonstrate the applicant’s commitment to learning and growth in the field?", 2),
    (21, "Soft Skills", "Does the CV reflect key soft skills required for the position such as collaboration, problem-solving, and attention to detail?", 4),
    (22, "Collaboration", "Are there mentions of teamwork or projects that required cross-functional collaboration?", 3),
    (23, "Teamwork Approach", "Does the applicant describe their approach to challenges or teamwork? Does this align with the company’s values?", 3),
    (24, "Cultural Alignment", "Are there any volunteer activities, memberships, or interests listed that resonate with the company's culture or values?", 3),
    (25, "Motivation and Passion", "Does the applicant express their motivation and passion for the field, and does it align with the company's mission and vision?", 2)
]